# frozen_string_literal: true

# Step 3 of the railsification — Microsoft 365 / Entra ID SSO via Devise +
# omniauth-entra-id (cf. autodev/docs/autospec.md §A and §C).
#
# Minimal config: only the Devise modules wired onto User (`:omniauthable`,
# `:trackable`) need configuration here. We skip `:database_authenticatable`
# entirely — there are no passwords, only Microsoft tenant accounts — and
# therefore none of the mailer / recoverable / confirmable settings are used.
#
# Credentials come from ENV. When unset (e.g. local dev without Entra
# registration), omniauth still mounts the provider but the actual login
# flow will fail at the redirect step. That keeps `bin/rails server` from
# 500ing at boot just because credentials are missing.
#
# To register the app in the Azure portal and obtain credentials, see
# https://github.com/RIPAGlobal/omniauth-entra-id#entra-id-server-configuration
#
# We require gems explicitly because `config/application.rb` skips
# `Bundler.require(*Rails.groups)` to keep Sinatra/Sequel out of the Rails
# process — which also means devise / omniauth aren't auto-required by
# bundler at boot.

require 'devise'
require 'omniauth-entra-id'
require 'omniauth/rails_csrf_protection'

# Keep OmniAuth 2.x's `allowed_request_methods = [:post]` default — the
# request phase only triggers via the POST form on /sign_in
# (SignInController).
#
# We DON'T however route through omniauth-rails_csrf_protection's
# TokenVerifier. The gem (1.0.2) raises InvalidAuthenticityToken even
# for valid form tokens under our Rails 8 + ActiveRecord::SessionStore
# combo (origin check passes — confirmed via the unverified_request_
# warning_message text — but the masked-token-vs-session-:_csrf_token
# comparison fails consistently; first hit on bobette during the
# alpha.13 verification). The OAuth `state` parameter (generated by
# OmniAuth at request phase, validated on callback) is the canonical
# CSRF defence for the OAuth handshake. Combined with the POST-only
# request method, the registered redirect_uri at Entra, and the
# NetBird mesh trust model, the defence-in-depth posture stays
# reasonable.
OmniAuth.config.request_validation_phase = nil

Devise.setup do |config|
  # Required by Devise even when no mailer-related module is active.
  config.mailer_sender = ENV.fetch('AUTODEV_MAILER_SENDER', 'noreply@autodev.local')

  # Devise normally picks this up from Rails' secret_key_base, but the minimal
  # railtie setup in `config/application.rb` doesn't pull in the secret_key
  # railtie, so we have to set it explicitly. Falls back to a generated value
  # in dev/test if no master key is configured.
  config.secret_key = Rails.application.secret_key_base || SecureRandom.hex(64)

  require 'devise/orm/active_record'

  config.case_insensitive_keys = [:email]
  config.strip_whitespace_keys = [:email]

  # `:http_auth` would otherwise stash creds in the session on every basic-auth
  # request — irrelevant here, kept on the default to avoid surprising Devise.
  config.skip_session_storage = [:http_auth]

  # Tighter than Devise's default — anything below 8 lets bcrypt round-trip
  # faster but is moot since we don't store passwords.
  config.stretches = Rails.env.test? ? 1 : 12

  config.reset_password_within = 6.hours
  config.sign_out_via = :delete

  # Entra ID provider. Tenant scoped to a single org by default; pass
  # `tenant_id: 'common'` to allow any work/school account.
  #
  # Stub credentials when ENV is unset, so:
  #  - `bin/rails server` boots in local dev without crashing — visiting
  #    `/users/auth/entra_id` will fail at the Azure redirect, which is the
  #    expected and visible failure mode.
  #  - integration tests can run `OmniAuth.config.test_mode = true` without
  #    the strategy's middleware-build step exploding on a nil client_id
  #    (the underlying oauth2 gem refuses to construct a Client with
  #    nil credentials, even when test_mode short-circuits the request).
  # Read Azure credentials in priority order: ENV → ~/.autodev/config.yml
  # → stub. The config-file path is what production typically uses since
  # launchd's env doesn't inherit the operator's shell vars; the ENV path
  # is convenient for one-off `bin/rails console` sessions.
  #
  # We can't read through `Web.config` here — that's populated by
  # `config/initializers/load_autodev_config.rb`'s `to_prepare`
  # block, which fires AFTER every initializer (including this one) has
  # run. Devise's `config.omniauth` call must happen synchronously here
  # so the Engine's middleware-build step picks the args up — by then,
  # the values are immutable. Read the YAML directly instead.
  azure_config = begin
    cfg_path = File.expand_path(ENV.fetch('AUTODEV_CONFIG', '~/.autodev/config.yml'))
    yaml = File.exist?(cfg_path) ? YAML.safe_load_file(cfg_path, aliases: true) : {}
    yaml.is_a?(Hash) ? (yaml['azure'] || {}) : {}
  rescue StandardError
    {}
  end

  config.omniauth :entra_id, {
    client_id: ENV.fetch('AZURE_AD_CLIENT_ID', azure_config['client_id'] || 'stub-client-id'),
    client_secret: ENV.fetch('AZURE_AD_CLIENT_SECRET',
                             azure_config['client_secret'] || 'stub-client-secret'),
    tenant_id: ENV.fetch('AZURE_AD_TENANT_ID', azure_config['tenant_id'] || 'common'),

    # CRITICAL: OmniAuth strategies match `/auth/:provider` by default,
    # but Devise's `devise_for :users` builds routes at
    # `/users/auth/:provider`. Without an explicit path_prefix the
    # middleware never sees the request and Devise falls back to
    # `Users::OmniauthCallbacksController#passthru` (a hardcoded 404).
    # Set this to the scope path so the strategy's request_path /
    # callback_path align with what `user_omniauth_authorize_path`
    # produces. Hit during the alpha.7 → alpha.8 cutover on bobette.
    path_prefix: '/users/auth'
  }
end

# alpha.7 → alpha.8 hotfix: `Devise.parent_controller` defaults to
# `ApplicationController`, so Devise's own controllers (sessions,
# omniauth_callbacks, the failure_app's redirect target) inherited
# `before_action :authenticate_user!` once PR3 turned it on globally.
# That caused `/users/sign_in` to itself require an authenticated user
# → Devise redirected back to `/users/sign_in` → loop →
# `ERR_TOO_MANY_REDIRECTS` in the browser (and a flood of
# `Completed 401 Unauthorized` in `production.log`).
#
# Two-part fix:
#   1. Strip `authenticate_user!` off the Devise parent class so every
#      Devise controller is reachable to anonymous traffic.
#   2. Replace the FailureApp so unauthenticated requests redirect
#      straight to `/users/auth/entra_id` (the omniauth handshake)
#      rather than `/users/sign_in` — the latter would render Devise's
#      default sessions/new view, which expects `:database_authenticatable`
#      fields we don't have.
Rails.application.config.to_prepare do
  DeviseController.skip_before_action :authenticate_user!, raise: false
end

# Custom FailureApp: skip the new_user_session_path detour, point
# every unauthenticated redirect at /sign_in (rendered by
# SignInController), which hands the user a button POSTing to the
# omniauth strategy with a CSRF token. We keep super's behaviour for
# HTTP-auth callers (xhr / api) and only override the HTML
# navigational redirect URL.
class EntraIdFailureApp < Devise::FailureApp
  def redirect_url
    return super unless scope == :user

    "#{request.base_url}/sign_in"
  end
end

Devise.warden do |manager|
  manager.failure_app = EntraIdFailureApp
end
