# frozen_string_literal: true

require 'sinatra/base'
require 'phlex'

require_relative 'web/event_bus'
require_relative 'web/helpers'
require_relative 'web/views/components/status_pill'
require_relative 'web/views/components/icon'
require_relative 'web/views/components/card'
require_relative 'web/views/components/button'
require_relative 'web/views/components/icon_button'
require_relative 'web/views/components/logo'
require_relative 'web/views/components/kpi'
require_relative 'web/views/components/sparkline'
require_relative 'web/views/components/topbar'
require_relative 'web/views/components/sidebar'
require_relative 'web/views/base'
require_relative 'web/views/layout'
require_relative 'web/views/dashboard'
require_relative 'web/views/issue_show'
require_relative 'web/views/errors'
require_relative 'web/views/project_show'
require_relative 'web/views/list'
require_relative 'web/views/issues'
require_relative 'web/server'
